export interface Product {
    productClass: string,
    productInitial: string,
    productName: string,
    licene: string,
    agent: string,
    technologyClass: string,
    technology: string,
    tickets: number,
    sales: number,
    earning: number,
}

export const TopSelling: Product[] = [

    {
        productClass: 'btn-info',
        productInitial: 'E',
        productName: 'Elite Admin',
        licene: 'Single Use',
        agent: 'John Doe',
        technologyClass: 'label-danger',
        technology: 'Angular',
        tickets: 46,
        sales: 356,
        earning: 2850.0,
    },
    {
        productClass: 'btn-orange',
        productInitial: 'M',
        productName: 'Monster Admin',
        licene: 'Single Use',
        agent: 'Venessa Fern',
        technologyClass: 'label-info',
        technology: 'Vue Js',
        tickets: 46,
        sales: 356,
        earning: 2850.0,
    },
    {
        productClass: 'btn-success',
        productInitial: 'M',
        productName: 'Material Pro Admin',
        licene: 'Single Use',
        agent: 'John Doe',
        technologyClass: 'label-success',
        technology: 'Bootstrap',
        tickets: 46,
        sales: 356,
        earning: 2850.0,
    },
    {
        productClass: 'btn-purple',
        productInitial: 'A',
        productName: 'Ample Admin',
        licene: 'Single Use',
        agent: 'John Doe',
        technologyClass: 'label-purple',
        technology: 'React',
        tickets: 46,
        sales: 356,
        earning: 2850.0,
    },

]